# ========== DATA ==========
image_folder: data/images
metadata_path: data/metadata.jsonl
image_size: 64

# ========== MODEL ==========
pretrained_vae: epoch49.pt
base_ch: 64
z_ch: 4

# ========== TRAINING ==========
batch_size: 256
learning_rate: 1e-4
num_epochs: 50
beta: 0.0005
num_workers: 2

out_dir: outputs/vae

# Logging & checkpoints
log_every: 1
save_every: 5
val_every: 1

push_to_hf: False
