# ========== DATA ==========
dataset_name: splcher/animefacedataset
metadata_name: metadata_lowres.jsonl
image_size: 64

# ========== MODEL ==========
base_ch: 128
disc_ch: 128
z_ch: 8
factor: 4
num_head: 8
architecture: vae-gan

# ========== LOSS ==========
kl_beta: 0.0005
w_charb: 1.0
w_lpips: 1.0
w_gan: 0.1

# ========== TRAINING & OPTIMIZER ==========
batch_size: 128
learning_rate: 1e-4
d_lr_scale: 1.0
num_epochs: 100
adam_beta1: 0.5
adam_beta2: 0.999
num_workers: 1

out_dir: outputs/vae_gan

# Logging & checkpoints
log_every: 1
save_every: 5
val_every: 1

push_to_hf: True
test_pipeline: True