# ========== DATA ==========
dataset_name: splcher/animefacedataset
metadata_name: metadata_lowres.jsonl
image_size: 512

# ========== MODEL ==========
base_ch: 128
z_ch: 4
factor: 8

# ========== TRAINING ==========
batch_size: 1
learning_rate: 1e-4
num_epochs: 100
beta: 0.0005
num_workers: 2

out_dir: outputs/vae_lowres

# Logging & checkpoints
log_every: 1
save_every: 5
val_every: 1

push_to_hf: False